### ISSUE TITLE
Request construction

### ISSUE THREAD

**Issue by DevZe** [izinkabi/HandymanWorkspace#12]
All the minimum requirements of a request component, including models, basic API cruid methods and private attributes like in Libraries constructors.

**Comment by DevNathi** [comment]
I think we can't really begin trying to sort out the request if we haven't sorted out the Services first. If we get those done it will be easy to construct the request because we will already know what to expect from both customer and service provider

**Comment by DevZe** [comment]
We trying to separate concerns by that and allow cohesion at a base level
